<a href="https://colab.research.google.com/github/ucfilho/Biochemical_Engineering/blob/master/Courses/EngBioq_2024_01/Aula_01_maio_22_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
x = 3
y = 4
z = x * y
print(x,y,z)

3 4 12


In [2]:
print(x**y)

81


In [3]:
print(y % x)

1


In [4]:
lista = [1,2,3,4,5,6,7,8]
for wi in lista:
  if wi % 2 == 0:
    print(wi,'numero par')
  else:
    print(wi,'numero impar')

1 numero impar
2 numero par
3 numero impar
4 numero par
5 numero impar
6 numero par
7 numero impar
8 numero par


In [5]:
pi = 3.141516
Vol = 600 # volume em metros cubicos
d = (4*Vol/pi)**(1/3) # diametro tanque com altura igual diametro
print('diametro:', d, 'metros')
di = d/3
print('diametro do agitador:', di, 'metros')

diametro: 9.141637346037356 metros
diametro do agitador: 3.047212448679119 metros


In [6]:
pi = 3.141516
Vol = 600 # volume em metros cubicos
d = (4*Vol/pi)**(1/3) # diametro tanque com altura igual diametro
print(f'diametro: {d:.2f} metros')
di = d/3
print(f'diametro do agitador:{di:.2f} metros')

diametro: 9.14 metros
diametro do agitador:3.05 metros


In [7]:
pi = 3.141516
Vol = [400,500,600,700,800,1000] # lista de volumes em metros cubicos
for Vi in Vol:
  d = (4*Vi/pi)**(1/3) # diametro tanque com altura igual diametro
  di = d/3
  print(f'diametro: {d:.2f} metros  diametro do agitador:{di:.2f} metros')

diametro: 7.99 metros  diametro do agitador:2.66 metros
diametro: 8.60 metros  diametro do agitador:2.87 metros
diametro: 9.14 metros  diametro do agitador:3.05 metros
diametro: 9.62 metros  diametro do agitador:3.21 metros
diametro: 10.06 metros  diametro do agitador:3.35 metros
diametro: 10.84 metros  diametro do agitador:3.61 metros


In [8]:
import numpy as np # importa a biblioteca numpy

In [9]:
import numpy as np # importa a biblioteca numpy
alpha= np.pi/4
print(np.sin(alpha),np.cos(alpha),np.tan(alpha))
N0_N = 1e10 # razao entre as concentracoes entrada e saida do filtro
print('LRV do filtro: ', np.log10(N0_N))


0.7071067811865475 0.7071067811865476 0.9999999999999999
LRV do filtro:  10.0


In [10]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]]) # fornecendo uma matriz
print(matriz) # imprime a matriz
print(matriz.shape) # dimensao da matriz
print(np.linalg.det(matriz)) # calculo do determinante
print(np.linalg.eigvals(matriz)) # calculo dos autovalores

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
0.0
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]


In [11]:
# fazendo uma regressao linear com o numpy:
x = [1,2,3,4]
y = [3,5,7,9] # neste caso y = 2x+1
a,b = np.polyfit(x,y,1)
print(a,b)

2.0000000000000004 0.9999999999999974


In [12]:
# fazendo regressao linear usando a biblioteca sklearn
from sklearn.linear_model import LinearRegression
# fazendo uma regressao linear com o numpy:
x = [1,2,3,4]
y = [3,5,7,9] # neste caso y = 2x+1
x = np.array(x).reshape(-1,1) #alterando o formato para forma que a biblioteca usa
y = np.array(y) # alterando o formato para forma q biblioteca aceita
reg = LinearRegression().fit(x,y) # ajuste do modelo
# impressao das informacoes .coef_ e  .intercept_ que estao dentro do modelo reg
print(reg.coef_,reg.intercept_)
r_sq = reg.score(x, y)
print(f"R^2: {r_sq}")

[2.] 1.0
R^2: 1.0


In [13]:
# tipos de dados
a = [1,2,3] # lista
b = np.array([1,2,3]) # numpy array
c = (1,2,3) # tuple
d = {1,2,3,2} # set


In [14]:
d

{1, 2, 3}